- riglib/e3vision.py
Change `E3VisionInterface.start_rec()` behavior to only change rec state for connected and synced cameras
> E3vision interface

- db/tracker/models.py
maybe this will fix the web interface?
> ignore is_bmi_seed if there is no data

- built_in_tasks/target_tracking_task.py
Previously, tracking task only had a "ramp" option to specify the duration of the ramp at the trial start. I've added a "ramp down" option to specify the duration of a ramp at the trial end. This helps avoid the cursor jumping due to the sudden addition/removal of the disturbance.
> create downramp that is independent from ramp

- built_in_tasks/target_tracking_task.py
- db/tracker/ajax.py
- features/__init__.py
- features/neuropixel_features.py
- riglib/experiment/task_wrapper.py
- riglib/open_ephys.py
- tests/test_neuropixel.py
Added neuropixel feature to record data with neuropixels
> Neuropixel

- built_in_tasks/bmimultitasks.py
- features/sync_features.py
- riglib/bmi/bmi.py
- riglib/bmi/kfdecoder_fcns.py
- riglib/bmi/lindecoder.py
some minor changes to bmi task
- fix cursor reset for lindecoder
- fix some nan issues with cursor analog sync
- change training to use taskentry.id instead of te_id
> Bmi hotfix

- built_in_tasks/bmimultitasks.py
- built_in_tasks/target_capture_task.py
- fixed reset so it works with center out
- added option to reset only after timeout penalty
- fixed the assister to work properly if needed
> fix bmi reset and assist

- built_in_tasks/target_tracking_task.py
- db/tracker/templates/list.html
- features/reward_features.py
- reward_server/web_server.py
Multi reward, manual reward, 1D fix
> Update tablet reward options

- config/rig_defaults.py
- setup.py
an extra comma is causing problems for the servers
> delete extra comma

- config/rig_defaults.py
I just deleted the comma that was causing optitrack path error on siburet rig :D
> fix optitrack path bug

- analysis/online_analysis.py
Work in Progress
- making a buffer for the eye_diameters to display as a constantly updating plot
> Plotting eye_diameter in BehaviorOnlineAnalysis

- built_in_tasks/target_capture_task.py
- features/optitrack_features.py
- riglib/stereo_opengl/primitives.py
- riglib/stereo_opengl/window.py
- tests/test_tasks.py
- add options for 3d projection and anaglyph into gui
- cap cylinder ends
> 3d projections for a 2d screen

- built_in_tasks/manualcontrolmultitasks.py
- features/peripheral_device_features.py
Read the values from a usb joystick using pygame. 
Currently working except if you move the mouse cursor onto the BMI computer it stops working.
> Joystick feature

- features/hdf_features.py
should be able to recover these temp hdf files even if the computer restarts. needs testing on the rig computer
> move tmp hdf files to /var/tmp

- built_in_tasks/target_graphics.py
- features/reward_features.py
- riglib/stereo_opengl/environment.py
- riglib/stereo_opengl/primitives.py
- riglib/stereo_opengl/render/stereo.py
- riglib/stereo_opengl/shaders/none.f.glsl
- riglib/stereo_opengl/shaders/phong.f.glsl
- riglib/stereo_opengl/textures.py
- riglib/stereo_opengl/utils.py
- riglib/stereo_opengl/window.py
- setup.py
- tests/test_graphics.py
- tests/test_tasks.py
made some adjustments to texture rendering to allow for transparent backgrounds on text
> text transparency

- features/laser_features.py
add option to restrict the trial index
> update laser state feature

- built_in_tasks/example_task.py
- built_in_tasks/force_task.py
- tests/test_tasks.py
add a simple example task to make new task development easier
> example task

- built_in_tasks/manualcontrolmultitasks.py
we can use `exp_scale` to adjust the gain and `scale` only to convert from the raw input coordinates to bmi3d coordinates in cm.
> add exp scale

- riglib/experiment/experiment.py
added trait num_rewarded_trials that ends experiment after a certain number of succesful trials. Default is 0, which will not end task based on succesful trials.
> add num_rewarded_trials feature

- built_in_tasks/manualcontrolmultitasks.py
- features/eyetracker_features.py
I checked that this "horizontal workspace" works with the glove and collected some test data in the booth.
> Katherine add horizontal workspace

- built_in_tasks/manualcontrolmultitasks.py
- built_in_tasks/target_capture_task.py
- built_in_tasks/target_tracking_task.py
- db/tracker/models.py
- setup.py
it's been a while since we updated bmi3d on pypi
> bump version
